AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SecurityGroupName:
    Description: RDS security group
    Type: String
  SubnetName:
    Description: RDSsubnet
    Type: String
Resources:
  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBSubnetGroupName: !Ref SubnetName
      MultiAZ: 'false'
      PubliclyAccessible: 'false'
      Engine: MySQL
      DBName: itzgiodb
      MasterUsername: giorgio
      MasterUserPassword: Contra1234.
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '5'
      VPCSecurityGroups:
        - !Ref SecurityGroupName
Outputs:
  DbInstanceEndpoint:
    Description: DBInstance endpoint
    Value: !GetAtt 
              - DBInstance
              - Endpoint.Address